<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="6" passed="2">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Suite Suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Chrome Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.facebookTitleCheck]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.facebookTitleCheck]]>
    </line>
    <line>
      <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.googleTitleCheck]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.googleTitleCheck]]>
    </line>
    <line>
      <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.failedRetryTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.failedRetryTest]]>
    </line>
    <line>
      <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing test Chrome Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Safari Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.facebookTitleCheck]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.facebookTitleCheck]]>
    </line>
    <line>
      <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.googleTitleCheck]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.googleTitleCheck]]>
    </line>
    <line>
      <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.beforeTest]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.failedRetryTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.failedRetryTest]]>
    </line>
    <line>
      <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : NewTest.afterTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : NewTest.afterTest]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="82423" started-at="2017-08-29T07:15:39Z" finished-at="2017-08-29T07:17:02Z">
    <groups>
    </groups>
    <test name="Chrome Test" duration-ms="40712" started-at="2017-08-29T07:15:39Z" finished-at="2017-08-29T07:16:20Z">
      <class name="Ashish.TestProject.NewTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="beforeTest" is-config="true" duration-ms="19423" started-at="2017-08-29T12:45:39Z" finished-at="2017-08-29T12:45:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="facebookTitleCheck()[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="facebookTitleCheck" duration-ms="7204" started-at="2017-08-29T12:45:59Z" finished-at="2017-08-29T12:46:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Ashish] but found [Facebook],
	expected [fail2] but found [fail1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Ashish] but found [Facebook],
	expected [fail2] but found [fail1]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Ashish.TestProject.NewTest.facebookTitleCheck(NewTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[About to begin executing following method : NewTest.facebookTitleCheck]]>
            </line>
            <line>
              <![CDATA[Completed executing following method : NewTest.facebookTitleCheck]]>
            </line>
            <line>
              <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
            <line>
              <![CDATA[About to begin executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- facebookTitleCheck -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="afterTest" is-config="true" duration-ms="844" started-at="2017-08-29T12:46:06Z" finished-at="2017-08-29T12:46:07Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="beforeTest" is-config="true" duration-ms="2852" started-at="2017-08-29T12:46:07Z" finished-at="2017-08-29T12:46:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="googleTitleCheck()[pri:1, instance:Ashish.TestProject.NewTest@5622fdf]" name="googleTitleCheck" duration-ms="1902" started-at="2017-08-29T12:46:10Z" finished-at="2017-08-29T12:46:12Z">
          <reporter-output>
            <line>
              <![CDATA[About to begin executing following method : NewTest.googleTitleCheck]]>
            </line>
            <line>
              <![CDATA[Completed executing following method : NewTest.googleTitleCheck]]>
            </line>
            <line>
              <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
            <line>
              <![CDATA[About to begin executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleTitleCheck -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="afterTest" is-config="true" duration-ms="781" started-at="2017-08-29T12:46:12Z" finished-at="2017-08-29T12:46:12Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="beforeTest" is-config="true" duration-ms="2095" started-at="2017-08-29T12:46:12Z" finished-at="2017-08-29T12:46:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="failedRetryTest()[pri:3, instance:Ashish.TestProject.NewTest@5622fdf]" name="failedRetryTest" duration-ms="4721" started-at="2017-08-29T12:46:14Z" finished-at="2017-08-29T12:46:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid] but found [Amazon]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid] but found [Amazon]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Ashish.TestProject.NewTest.failedRetryTest(NewTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[About to begin executing following method : NewTest.failedRetryTest]]>
            </line>
            <line>
              <![CDATA[Completed executing following method : NewTest.failedRetryTest]]>
            </line>
            <line>
              <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
            <line>
              <![CDATA[About to begin executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- failedRetryTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Ashish.TestProject.NewTest@5622fdf]" name="afterTest" is-config="true" duration-ms="834" started-at="2017-08-29T12:46:19Z" finished-at="2017-08-29T12:46:20Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Ashish.TestProject.NewTest -->
    </test> <!-- Chrome Test -->
    <test name="Safari Test" duration-ms="11546" started-at="2017-08-29T07:16:50Z" finished-at="2017-08-29T07:17:02Z">
      <class name="Ashish.TestProject.NewTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="beforeTest" is-config="true" duration-ms="4775" started-at="2017-08-29T12:46:50Z" finished-at="2017-08-29T12:46:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[safari]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="facebookTitleCheck()[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="facebookTitleCheck" duration-ms="2171" started-at="2017-08-29T12:46:55Z" finished-at="2017-08-29T12:46:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Ashish] but found [Facebook],
	expected [fail2] but found [fail1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Ashish] but found [Facebook],
	expected [fail2] but found [fail1]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Ashish.TestProject.NewTest.facebookTitleCheck(NewTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[About to begin executing following method : NewTest.facebookTitleCheck]]>
            </line>
            <line>
              <![CDATA[Completed executing following method : NewTest.facebookTitleCheck]]>
            </line>
            <line>
              <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
            <line>
              <![CDATA[About to begin executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- facebookTitleCheck -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="afterTest" is-config="true" duration-ms="305" started-at="2017-08-29T12:46:57Z" finished-at="2017-08-29T12:46:57Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="beforeTest" is-config="true" duration-ms="1268" started-at="2017-08-29T12:46:57Z" finished-at="2017-08-29T12:46:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[safari]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="googleTitleCheck()[pri:1, instance:Ashish.TestProject.NewTest@3fee9989]" name="googleTitleCheck" duration-ms="623" started-at="2017-08-29T12:46:59Z" finished-at="2017-08-29T12:46:59Z">
          <reporter-output>
            <line>
              <![CDATA[About to begin executing following method : NewTest.googleTitleCheck]]>
            </line>
            <line>
              <![CDATA[Completed executing following method : NewTest.googleTitleCheck]]>
            </line>
            <line>
              <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
            <line>
              <![CDATA[About to begin executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleTitleCheck -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="afterTest" is-config="true" duration-ms="61" started-at="2017-08-29T12:46:59Z" finished-at="2017-08-29T12:46:59Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="beforeTest" is-config="true" duration-ms="1206" started-at="2017-08-29T12:46:59Z" finished-at="2017-08-29T12:47:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[safari]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="failedRetryTest()[pri:3, instance:Ashish.TestProject.NewTest@3fee9989]" name="failedRetryTest" duration-ms="1056" started-at="2017-08-29T12:47:01Z" finished-at="2017-08-29T12:47:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid] but found [Amazon]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid] but found [Amazon]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Ashish.TestProject.NewTest.failedRetryTest(NewTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[About to begin executing following method : NewTest.failedRetryTest]]>
            </line>
            <line>
              <![CDATA[Completed executing following method : NewTest.failedRetryTest]]>
            </line>
            <line>
              <![CDATA[Test Method resides in Ashish.TestProject.NewTest]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
            <line>
              <![CDATA[About to begin executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- failedRetryTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Ashish.TestProject.NewTest@3fee9989]" name="afterTest" is-config="true" duration-ms="68" started-at="2017-08-29T12:47:02Z" finished-at="2017-08-29T12:47:02Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : NewTest.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Ashish.TestProject.NewTest -->
    </test> <!-- Safari Test -->
  </suite> <!-- Suite -->
</testng-results>
